# Generated by Django 4.2.6 on 2023-10-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
