# Generated by Django 4.2.6 on 2023-10-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_imgthumb200_imgthumb400_alter_img_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgEnterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ImgPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.RenameModel(
            old_name='Img',
            new_name='ImgBasic',
        ),
    ]
